### ISSUE TITLE
Doc Comparison - Add admin capabilities

### ISSUE THREAD

**Issue by sashatrubetskoy** [BlueWaveTechnologies/BlueWave#279]
@pborissow  Mentioned it would be nice to have a capability for admins to be able to clear the cache, and perform other slightly advanced maintenance tasks. This will require integrating an admin panel somewhere in the tool.

**Comment by markssss** [comment]
Use the following GET endpoint to hook into the UI refresh index button:
/document/RefreshDocumentIndex

**Comment by markssss** [comment]
Each test iteration should consist of:
1. Confirm bluewave app is NOT running
2. Delete BLUEWAVE_HOME/temp/index directory
3. java -jar target/bluewave-dev.jar -config config.json -delete index 
4. add a few documents/pdfs to the BLUEWAVE_HOME/temp/uploads dir
5. Start the bluewave app
6. confirm docs are present http://localhost:8080/DocumentAnalysis
7. Manually copy additional pdfs to the BLUEWAVE_HOME/temp/uploads dir
8. Now call/execute http://localhost:8080/document/RefreshDocumentIndex
9. confirm additional docs are present http://localhost:8080/DocumentAnalysis
10. Repeat
