### ISSUE TITLE
Bounding box sometimes totally off (e.g. small sliver on top of page)

### ISSUE THREAD

**Issue by sashatrubetskoy** [BlueWaveTechnologies/BlueWave#284]
For example the top of this page

![image](https://user-images.githubusercontent.com/8084066/167026111-c54d8244-b497-470f-922d-f80d8162cd6d.png)

**Comment by sashatrubetskoy** [comment]
Need to determine if this is a python issue or a JS rendering issue

**Comment by swordysrepo** [comment]
I noticed there are other rendering issues, sometimes it is double rendering tags/match boxes.

**Comment by swordysrepo** [comment]
Also I've been able to replicate the bounding box issue, because it happens inconsistently when a page is reloaded, I am sure that it a JS rendering issue
